buy/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name= 'buy'

urlpatterns = [
    path("payment/<int:id>/", payment, name='payment'),
    path("address/", address, name='address'),
    path("place_order/", place_order, name='place_order'),
    path("confirm_page/", confirm_page, name='confirm_page'),
    path("my_orders/", my_orders, name='my_orders'),
    # path("email/", email, name='email'),
]

cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static 
app_name = 'cart'

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('add_cart/<int:id>', views.add_cart, name='add_cart'),
    path("remove/<int:product_id>", views.remove, name="remove")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from search_components.views import search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("accounts.urls")),
    path('',include("products.urls")),
    path('',include("cart.urls")),
    path('',include("user_profile.urls")),
    path('',include("buy.urls")),

    path("search/", search, name="search")
]

products/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('product/', views.product, name='product'),
    path('laptops/', views.laptops, name='laptops'),
    path('mobiles/', views.mobiles, name='mobiles'),
    path('sensors/', views.sensors, name='sensors'),
    # path('rating/<id>', views.rating, name='rating'),
    path('<int:product_id>/', views.product, name='product'),
    path('electronic_components/', views.electronic_components, name='electronic_components'),
]

cart/models.py
from django.conf import settings
from django.db import models

from products.models import Product

User = settings.AUTH_USER_MODEL

class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE) 
    product = models.ForeignKey(Product,  null=True, blank=True, on_delete=models.CASCADE)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name

cart/views.py
from django.shortcuts import render, redirect
from cart.models import Cart
from django.http import HttpResponse
from django.contrib import messages
from products.models import Product
from django.contrib.auth.decorators import login_required
 
def cart(request):
    user = request.user
    cart_items = Cart.objects.filter(user=user.id).order_by('-updated')
    total, discount, mrp = 0,0,0
    for i in cart_items:
        mrp += i.product.mrp
        total += i.product.deal_price
        discount += (i.product.mrp - i.product.deal_price)
    context={
        'cart_items':cart_items,
        'mrp':mrp,
        'total':total,
        'discount':discount
        }
    return render(request, 'cart/cart.html', context)

# @login_required(login_url='/login/')
def add_cart(request, id):
    user = request.user
    product=Product.objects.get(id=id)
    if not Cart.objects.filter(user=user, product=product).exists():
        Cart.objects.create(user=user, product=product)
    return redirect("cart:cart")

def remove(request, product_id):
    user = request.user
    cart_item = Cart.objects.filter(user=user.id)
    if cart_item.filter(product_id=product_id):
        messages.success(request,'Item removed from cart successfully')
        cart_item.get(product_id=product_id).delete()
    else:
        messages.error(request,'Item is not in cart')
    return redirect("cart:cart")

templates/cart/cart.html
{% extends "accounts/base.html" %}
{% load static %}
{% block title %}Cart{% endblock %}
{% block style %}
<style>
    #container{
        margin: 10px 50px;
        padding: 100px;
    }
</style>
{% endblock %}

{% block content %}

<div class="cart_head">
    <h2 id='title'>Shopping Cart</h2> 
</div>
{% include 'partials/_alerts.html' %}
{% if cart_items %}
<div class="cart_content">
    <div class="shopping_cart">
<form action="">
    {% for cart_item in cart_items %}
        <div class="cart_item">
        <div></div>
        <a href="{% url 'products:product' cart_item.product.id %}">
            <div class="item_image"><img src="{{cart_item.product.main_image.url}}" alt="{{cart_item.product.title}}">
            </div></a>
        <div class="item_description">
            <a href="{% url 'products:product' cart_item.product.id %}"  style="color: black;">
                <h2>{{cart_item.product.title}}</h2>
            <div class="item_price">
                <h3>Rs.{{cart_item.product.deal_price}}</h3> 
                <del>Rs.{{cart_item.product.mrp}}</del>  
                <!-- <del>MRP</del> -->
            </div>
            </a>
            <div class="rating">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
            </div>
            <select name="quantity" id="">
                <option value="1">Qty: 1</option>
                <option value="2">Qty: 2</option>
                <option value="3">Qty: 3</option>
                <option value="4">Qty: 4</option>
                <option value="5">Qty: 5</option>
                <option value="6">Qty: 6</option>
                <option value="7">Qty: 7</option>
                <option value="8">Qty: 8</option>
                <option value="9">Qty: 9</option>
                <option value="10">Qty: 10</option>
            </select><br>
            <p style="display:inline;">No cost EMI Available</p>
            <a style="color: black; font-weight:bold; display:inline; margin-left:50px;" 
            href="{% url 'cart:remove' cart_item.product.id %}">REMOVE</a>
        </div>
        <!-- <div>
            Delivery by
        </div> -->
    </div>
    {% endfor %}
    <button class="btm-btn">Place Order</button>
</form>
</div>
<div class="price_details">
    <div style="font-weight: bold; ">PRICE DETAILS</div><div></div>
    <div>Price</div> <div>{{mrp}}</div>
    <div>D Price</div> <div>{{discount}}</div>
    <div>T Price</div> <div>{{total}}</div>
</div>
</div>

{% else %}
<h1 id="container">Cart is empty</h1>
{% endif %}
<br><br><br>
{% endblock %}