accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static 
app_name = 'accounts'

urlpatterns = [
#     path('signup/', views.signup, name='signup'),
    path('signup/', views.signup1, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', 
            views.activate, name='activate'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('new_password/<str:trans_id>', views.new_password, name='new_password'),
    path('change_password/', views.change_password, name='change_password'),
    path('verify_otp/<str:trans_id>/', views.verify_otp, name='verify_otp'),
    path('deactivate/', views.deactivate, name='deactivate'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

buy/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name= 'buy'

urlpatterns = [
    path("payment/<int:id>/", payment, name='payment'),
    path("address/", address, name='address'),
    path("place_order/", place_order, name='place_order'),
    path("confirm_page/", confirm_page, name='confirm_page'),
    path("my_orders/", my_orders, name='my_orders'),
    # path("email/", email, name='email'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from search_components.views import search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("accounts.urls")),
    path('',include("products.urls")),
    path('',include("cart.urls")),
    path('',include("user_profile.urls")),
    path('',include("buy.urls")),

    path("search/", search, name="search")
]

products/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('product/', views.product, name='product'),
    path('laptops/', views.laptops, name='laptops'),
    path('mobiles/', views.mobiles, name='mobiles'),
    path('sensors/', views.sensors, name='sensors'),
    # path('rating/<id>', views.rating, name='rating'),
    path('<int:product_id>/', views.product, name='product'),
    path('electronic_components/', views.electronic_components, name='electronic_components'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser

class EmailOTP(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    trans_id = models.CharField(max_length=15, unique=True)
    created_at = models.DateTimeField(auto_now=True)
    otp = models.IntegerField()
    def __str__(self):
        return str(self.otp)

accounts/forms.py
from django import forms

class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=20, required=True, label="First Name", widget=forms.TextInput(attrs={'placeholder':'First Name'}))
    last_name = forms.CharField(max_length=20, required=True,  label="Last Name", widget=forms.TextInput(attrs={'placeholder':'Last Name'}))
    email = forms.EmailField(max_length=100, required=True, widget=forms.TextInput(attrs={'placeholder':'Email'}))
    mobile = forms.CharField(max_length=20, required=False, label="Mobile Number", widget=forms.TextInput(attrs={'placeholder':'Mobile Number', 'pattern':'[6-9]\d{9}'}))
    # gender = forms.ChoiceField(choices=[("Male", "Male"), ("Femal","Female")], required=False, widget=forms.RadioSelect)
    password = forms.CharField(max_length=20, required=True, widget=forms.PasswordInput(attrs={'placeholder':'Password'}))

accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string, get_template
from .tokens import account_activation_token
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.contrib.auth.models import User
from django.contrib import auth, messages
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.views.decorators.csrf import csrf_protect
from django.http import HttpResponse
from django.contrib.auth import get_user_model
import math, random
import uuid
from user_profile.models import *
from .models import *
from cart.models import Cart
from django.contrib import messages
from .forms import SignupForm


# Generate OTP
def generate_otp():
    digits = "0123456789"
    OTP = ""
    for i in range(6):
        OTP += digits[math.floor(random.random() * 10)]
    trans_id = uuid.uuid4().hex[:15]
    return OTP,trans_id

# Verify OTP
def verify_otp(request, trans_id):
    if request.method=="POST":
        otp = request.POST['otp']
        if EmailOTP.objects.filter(trans_id=trans_id, otp=otp).exists():
            return HttpResponseRedirect(reverse('accounts:new_password', kwargs={"trans_id":trans_id}))
        else:
            messages.error(request, "wrong otp")
            return HttpResponseRedirect(reverse('accounts:verify_otp', kwargs={"trans_id":trans_id}))
    return render(request, 'accounts/otp.html')


def signup(request):
    if request.method == 'POST':
        username = request.POST['email']
        email = request.POST['email']
        full_name = request.POST['name'].title()
        password = request.POST['password']
        mobile = request.POST['mobile']
        if User.objects.filter(email=email).exists():
            messages.error(request, 'Email is already registered')
            return render(request, 'accounts/signup.html')
        if ProfileInfo.objects.filter(mobile=mobile).exists():
            messages.error(request, 'Mobile Number is already registered')
            return render(request, 'accounts/signup.html')
        user = User.objects.create_user(username=email, email=email, password=password, first_name=full_name)
        user.is_active = False
        user.save()
        ProfileInfo.objects.create(user=user, mobile=mobile)
        current_site = get_current_site(request)
        mail_subject = 'Activate your account.'
        message = render_to_string('email_temp_html.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
        to_email = email
        email = EmailMultiAlternatives(mail_subject, message, to=[to_email])
        email.attach_alternative(message, "text/html")
        email.send()
        messages.success(request, 'Verify your email and login')
        return render(request, 'accounts/login.html')
    return render(request, 'accounts/signup.html')


def activate(request, uidb64, token):
    user = get_user_model()
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = user.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Email Verified successfully')
        return render(request, 'accounts/login.html')
    else:
        return HttpResponse('Activation link is invalid!')


@csrf_protect
def login(request):
    if request.method == 'POST':
        email = request.POST['username']
        user = User.objects.filter(email=email)
        # username = user.username
        password = request.POST['password']
        user = auth.authenticate(username=email, password=password)
        if user is not None:
            auth.login(request,user)
            messages.success(request,'Loged in successfully')
            return redirect('products:index')
        elif not User.objects.filter(username=email):
            messages.error(request,'email or mobile is not registered')
            return redirect("accounts:signup")
        elif not User.objects.get(username=email).is_active:
            messages.error(request,'email is not verified')
            return redirect("accounts:login")
        else:
            messages.error(request,' Invalid username or password')
    return render(request, 'accounts/login.html')


def logout(request):
    auth.logout(request)
    messages.success(request,'Loged out successfully')
    return redirect('products:index')

def forgot_password(request):
    if request.method=="POST":
        email = request.POST['email']
        if User.objects.filter(email=email).exists():
            user = User.objects.get(email=email)
            otp, trans_id = generate_otp()
            EmailOTP.objects.create(user=user, otp=otp, trans_id=trans_id)
            mail_subject = 'OTP to reset password.'
            message = render_to_string('email_otp.html', {
                        'user': user,
                        'otp':otp,
                    })
            to_email = email
            email = EmailMultiAlternatives(mail_subject, message, to=[to_email])
            email.attach_alternative(message, "text/html")
            email.send()

            return HttpResponseRedirect(reverse('accounts:verify_otp', kwargs={"trans_id":trans_id}))
        else:
            messages.error(request, "user is not registered")
    return render(request, "accounts/forgot_password.html")


def new_password(request, trans_id):
    if request.method=="POST":
        password = request.POST['password']
        password2 = request.POST['password2']
        if password==password2:
            user = EmailOTP.objects.get(trans_id=trans_id).user_id
            user = User.objects.get(id=user)
            EmailOTP.objects.get(trans_id=trans_id).delete()
            user.set_password(password)
            user.save()
            messages.success(request, "Password changed succesfully")
            return redirect("accounts:login")
        else:
            messages.error(request, "Passwords must be same")
            return HttpResponseRedirect(reverse('accounts:new_password', kwargs={"trans_id":trans_id}))
    return render(request, 'accounts/new_password.html')


def change_password(request):
    user = request.user
    if request.method=="POST":
        old_password = request.POST['old_password']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if user.check_password(old_password):
            if password1 == password2:
                user.set_password(password1)
                user.save()
                messages.success(request, "Password changed succesfully")
                return redirect("user_profile:profile")
            else:
                messages.error(request,"Password should be same")
                return redirect("accounts:change_password")
        else:
            messages.error(request,"Old Password is wrong")
            return redirect("accounts:change_password")

    if user.is_authenticated:
        return render(request, 'accounts/change_password.html')
    else:
        return redirect("accounts:login")


def deactivate(request):
    user =request.user
    if request.method=="POST":
        password = request.POST['password']
        if user.check_password(password):
            User.objects.get(id=user.id).delete()
            if Cart.objects.filter(user_id=user.id).exists():
                Cart.objects.filter(user_id=user.id).delete()
            if ProfileInfo.objects.filter(user_id=user.id).exists():
                ProfileInfo.objects.get(user_id=user.id).delete()
            if Address.objects.filter(user_id=user.id).exists():
                Address.objects.filter(user_id=user.id).delete()
            if Card.objects.filter(user_id=user.id).exists():
                Card.objects.filter(user_id=user.id).delete()
            messages.success(request, "account deactivated")
            return redirect("products:index")
        else:
            messages.error(request, "wrong password")
            return redirect("accounts:deactivate")
    if user.is_authenticated:
        return render(request, 'accounts/deactivate.html')
    else:
        return redirect("accounts:login")


def signup1(request):
    if request.method=="POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            mobile = form.cleaned_data.get('mobile')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')

            # check email is already registered or not
            if User.objects.filter(email=email).exists():
                messages.error(request, "user already registed with this email {}".format(email))
                return render(request,"accounts/signup1.html", context={"form": form})

            # check mobile number is already registered or not
            if ProfileInfo.objects.filter(mobile=mobile).exists():
                messages.error(request, "user already registed with this number {}".format(mobile))
                return render(request,"accounts/signup1.html", context={"form": form})

            user = User.objects.create_user(username=email, email=email, password=password, first_name=first_name, last_name=last_name)
            user.is_active = False
            user.save()

templates/accounts/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/user.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    {% comment %} <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> {% endcomment %}
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}<style></style>{% endblock %}
</head>
<body>
    <nav>
        <a href="{% url 'products:index' %}"><label class='logo'>SHOPIFY</label></a>
    </nav>
    
        {% block content %}
          
        {% endblock %}

    <div class="footer">
        <a href="#">About us</a> 
        <a href="#">Condition of Use and Sale</a> 
        <a href="#">Privacy Notice</a><br>
        <a href="#">Facebook</a> 
        <a href="#">Twitter</a> 
        <a href="#">Instagram</a> 
        <p>&copy;2020 SHOPIFY</p>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    setTimeout(function() {
        $('#message').fadeOut('fast');
    }, 3000);
</script>
</body>

templates/accounts/change_password.html
{% extends 'accounts/base.html' %}

{% block title %}
Change Password
{% endblock %}

{% block styles %}
<style>
    input[type=submit]{
        margin-left:-120px;
    }
    input[type=reset]{
        color: white;
        font-weight: bold;
        border-radius: 20px;
        padding: 10px 30px;
        position: absolute;
        transform: translate(-50%);
        border: 2px solid #07CB79;
        background: black;
        outline: none;
        box-shadow: 0 0 5px black;
        left:310px;
    }
    .mid-box{
        height: auto;
    }
    form{
        margin-bottom: 50px;
    }
</style>
{% endblock %}
{% block content %}
    <div class="mid-box">
        <form method="POST">
            {% csrf_token %}
            {% include "partials/_alerts.html" %}
            <h1>Change Password</h1>
            <p>Old Password</p>
            <input type="password" placeholder="Old Password" name='old_password' required>
            <p>New Password</p>
            <input type="password" placeholder="Password" name='password1'>
            <input type="password" placeholder="Confirm Password" name='password2'>
            <div class="buttons"><br>
                <input type="submit" value="Submit">
                <input type="reset" value="Cancel">
            </div>        
        </form>
    </div>
{% endblock %}

templates/accounts/deactivate.html
{% extends 'accounts/base.html' %}

{% block title %}
Deactivate
{% endblock %}

{% block styles %}
<style>
    input[type=submit]{
        margin-left:-120px;
    }
    input[type=reset]{
        left:310px;
    }
</style>
{% endblock %}

{% block content %}
    <div class="mid-box">
        <form method="POST">
            {% csrf_token %}
            <h1>Deactivate Account</h1>
            {% include "partials/_alerts.html" %}
            <p>Password</p>
            <input type="password" placeholder="Password" name='password'>
            <div class="buttons"><br>
                <input type="submit" value="Submit">
                <input type="reset" value="Cancel">
            </div>        
        </form>
    </div>
{% endblock %}

templates/accounts/forgot_password.html
{% extends 'accounts/base.html' %}
{% block title %}
Forgot Password
{% endblock %}
    {% block styles %}
<style>
    input[value="Submit"]{
        margin-left: -80px;
    }
    input[value="Cancel"]{
        margin-left: 30px;
    }
    .mid-box{
        height: 300px;
    }
    form{
        margin-bottom: 50px;
    }

    .mid-box span::before{
        content: "I have an account? ";
}   
</style> 
    {% endblock  %}

{% block content %}
    <div class="mid-box">
        <form class="signup" style="height: 55%; padding-bottom:385px;"><br>
        {% csrf_token %}
            <h1>Forgot Password</h1>
            <p>Enter Email or Mobile</p>
            <input type="text" placeholder="Email or Mobile" required><br><br>
            <input type="submit" value="Submit">
            <input type="submit" value="Cancel">
            <!-- <button style="float: right;">Cancel</button><br><br><br> -->
            <br><br><span><a href="{% url 'accounts:login' %}">Login</a></span>
        </form>
    </div>
    
{% endblock %}

templates/accounts/login.html
{% extends "accounts/base.html" %}
{% block title %}
  Login
{% endblock %}
{% block styles %}
<style>
    .mid-box span::before{
        content: "Already have an account? ";
    }  
</style>
{% endblock %}        

{% block content %}
    <div class="mid-box" >
    {% include 'partials/_alerts.html' %}
        <form class="signup" method='POST' action="{% url 'accounts:login' %}"><br>
          {% csrf_token %}
            <h1 align='center'>Login</h1>
            <p>Email or Mobile Number</p>
            <input type="text" placeholder="Email or Mobile Number" required name='username'><br>
            <p>Password</p>
            <input type="password" placeholder="Password" required name='password'><br>
        <div class="buttons">
            <input type="submit" value='Login'>
        </div>
        </form>
        <div class='devider'>
            <br><span><a href="{% url 'accounts:signup' %}">SignUp</a></span>
        </div><br>
        <div class='forgotp' style="line-height: 20px; margin-bottom:0;">
            <span><a href="{% url 'accounts:forgot_password' %}"><br> Forgot Password</a></span>
        </div><br>
        <p style="font-size: 12px;">By login, you agree to HKTECH SHOP's Conditions of Use and Privacy Notice.</p>
    </div>

{% endblock %}

templates/accounts/new_password.html
{% extends 'accounts/base.html' %}

{% block title %}
New Password
{% endblock %}

{% block styles %}
<style>
    input[type=submit]{
        margin-left:-120px;
    }
    input[type=reset]{
        color: white;
        font-weight: bold;
        border-radius: 20px;
        padding: 10px 30px;
        position: absolute;
        transform: translate(-50%);
        border: 2px solid #07CB79;
        background: black;
        outline: none;
        box-shadow: 0 0 5px black;
        left:320px;
    }
    .mid-box{
        height: auto;
    }
    form{
        margin-bottom: 50px;
    }
</style>
{% endblock %}
<body>
{% block content %}
<div class="mid-box"><br>
    <form method="POST">
        <h1>New Password</h1>
        {% csrf_token %}
        {% include 'partials/_alerts.html' %}
        <input type="password" placeholder="Password" name='password'>
        <input type="password" placeholder="Confirm Password" name='password2'>
        <div class="buttons"><br>
            <input type="submit" value="Submit">
            <input type="reset" value="Cancel">
        </div>       
    </form>
</div>  
{% endblock %}

templates/accounts/otp.html
{% extends 'accounts/base.html' %}
{% block title %}
Forgot Password
{% endblock %}
    {% block styles %}
<style>
    input[value="Submit"]{
        margin-left: -80px;
    }
    input[value="Cancel"]{
        margin-left: 30px;
    }
    .mid-box{
        height: 300px;
    }
    form{
        margin-bottom: 50px;
    }

    .mid-box span::before{
        content: "I have an account? ";
}   
</style> 
    {% endblock  %}

{% block content %}
    <div class="mid-box">
        <form class="signup" style="height: 55%; padding-bottom:385px;" method="POST"><br>
        {% csrf_token %}
            <h1>Verify OTP</h1>
            {% include 'partials/_alerts.html' %}
            <p> Enter OTP</p>
            <input type="text" placeholder="OTP" name='otp' required><br><br>
            <div class="buttons">
                <input type="submit" value="Submit">
                <input type="submit" value="Cancel">    
            </div>
        </form>
    </div>
    
{% endblock %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% block title %}Signup{% endblock %}

{% block styles %}
<style>
    .mid-box span::before{
        content: "Already have an account? ";
    }
</style>
{% endblock  %}

{% block content %}
<div class="mid-box">
    {% include 'partials/_alerts.html' %}
    <form class="signup" method='POST' style="height: 60%; padding-bottom:385px;"><br>
        {% csrf_token %}
        <h1 align='center'>Create Account</h1>
        <p>Name</p>
        <input type="text" placeholder="Name" name='name' required><br>
        <!-- <p>First Name</p>
        <input type="text" placeholder="First Name" name='first_name' required><br> -->
        <!-- <p>Last Name</p>
        <input type="text" placeholder="Last Name" name='last_name'><br>
        <p>Gender</p>
        <label for="male">Male</label>
        <input type="radio" name="gender" id="male" value='male'>
        <label for="female">Female</label>
        <input type="radio" name="gender" id="female" value='female'><br><br> -->
        <p>Mobile Number</p>
        <input type="text" placeholder="Mobile Number" name='mobile'><br>
        <p>Email</p>
        <input type="text" placeholder="Email" name='email'><br>
        <p>Password</p>
        <input type="password" placeholder="Password" name='password' required><br>
        <div class="buttons">
            <input type="submit" value="Signup">
        </div>
    </form>
    <div class="gap"><br></div>
        <div class='devider'>
            <span><a href="{% url 'accounts:login' %}">Login</a></span>
        </div>
    </div>
{% endblock %}

templates/accounts/signup1.html
{% extends "accounts/base.html" %}
{% block title %}
Signup
{% endblock %}

{% block styles %}
<style>
    .mid-box span::before{
        content: "Already have an account? ";
    }
</style>
{% endblock  %}

{% block content %}

<div class="mid-box"><br>

    <form method="POST">
        {% csrf_token %}
        <h1 align='center'>Create Account</h1>
        {% include "partials/_alerts.html" %}
        {{form}}
        <input type="submit" value="Signup">
    </form>
    <div class="gap"><br></div>
    <div class='devider'>
        <span><a href="{% url 'accounts:login' %}">Login</a></span>
    </div>

</div>

{% endblock %}