accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static 
app_name = 'accounts'

urlpatterns = [
#     path('signup/', views.signup, name='signup'),
    path('signup/', views.signup1, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', 
            views.activate, name='activate'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('new_password/<str:trans_id>', views.new_password, name='new_password'),
    path('change_password/', views.change_password, name='change_password'),
    path('verify_otp/<str:trans_id>/', views.verify_otp, name='verify_otp'),
    path('deactivate/', views.deactivate, name='deactivate'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

buy/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name= 'buy'

urlpatterns = [
    path("payment/<int:id>/", payment, name='payment'),
    path("address/", address, name='address'),
    path("place_order/", place_order, name='place_order'),
    path("confirm_page/", confirm_page, name='confirm_page'),
    path("my_orders/", my_orders, name='my_orders'),
    # path("email/", email, name='email'),
]

cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static 
app_name = 'cart'

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('add_cart/<int:id>', views.add_cart, name='add_cart'),
    path("remove/<int:product_id>", views.remove, name="remove")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from search_components.views import search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("accounts.urls")),
    path('',include("products.urls")),
    path('',include("cart.urls")),
    path('',include("user_profile.urls")),
    path('',include("buy.urls")),

    path("search/", search, name="search")
]

products/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('product/', views.product, name='product'),
    path('laptops/', views.laptops, name='laptops'),
    path('mobiles/', views.mobiles, name='mobiles'),
    path('sensors/', views.sensors, name='sensors'),
    # path('rating/<id>', views.rating, name='rating'),
    path('<int:product_id>/', views.product, name='product'),
    path('electronic_components/', views.electronic_components, name='electronic_components'),
]

user_profile/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
app_name= 'user_profile'

urlpatterns = [
    path("profile/", my_profile, name='profile'),
    path("del_card/<int:id>/", del_card, name='del_card'),
    path("del_addr/<int:id>/", del_addr, name='del_addr'),
    path("edit_addr/<int:id>/", edit_addr, name='edit_addr'),
    # path("del_addr/<int:id>/", del_addr, name='del_addr'),
]

products/models.py
from django.db import models


# class TechnicalDeatails(models.Model):

class Seller(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    asin = models.CharField(max_length=20)
    bsr = models.CharField(max_length=255)
    doa = models.DateField()

    def __str__(self):
        return self.name


class Category(models.Model):
    category = models.CharField(max_length=255)
    def __str__(self):
        return self.category

class Mobile(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    os = models.CharField(max_length=255, default="Android", blank=True, null=True)
    rom = models.CharField(max_length=5, blank=True, null=True)
    ram = models.CharField(max_length=5, blank=True, null=True)
    processor = models.CharField(max_length=50, blank=True, null=True)
    battery = models.CharField(max_length=50, blank=True, null=True)
    rating = models.IntegerField(blank=True, null=True)
    color = models.CharField(max_length=255, blank=True, null=True)
    item_dim = models.CharField(max_length=255, blank=True, null=True)
    item_weight = models.CharField(max_length=255, blank=True, null=True)
    item_model_no = models.CharField(max_length=255, blank=True, null=True)
    wireless_com_tech = models.CharField(max_length=255, blank=True, null=True)
    connectivity_tech = models.CharField(max_length=255, blank=True, null=True)
    speacial_features = models.CharField(max_length=255, default="Included")
    display_tech = models.CharField(max_length=255, blank=True, null=True)
    camera = models.CharField(max_length=255, blank=True, null=True)
    form_factor = models.CharField(max_length=255, blank=True, null=True)
    color = models.CharField(max_length=255, blank=True, null=True)
    battery_rating = models.CharField(max_length=255, blank=True, null=True)
    whats_in_box = models.CharField(max_length=255, blank=True, null=True)
    warrenty = models.CharField(max_length=255, default="1 Year", blank=True, null=True)
    
    def __str__(self):
        return self.title


class Laptop(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    brand = models.CharField(max_length=255, blank=True, null=True)
    series = models.CharField(max_length=255, blank=True, null=True)
    color = models.CharField(max_length=255, blank=True, null=True)
    item_height = models.CharField(max_length=255, blank=True, null=True)
    item_width = models.CharField(max_length=255, blank=True, null=True)
    item_weight = models.CharField(max_length=255, blank=True, null=True)
    screen_size = models.CharField(max_length=255, blank=True, null=True)
    maximum_display_res = models.CharField(max_length=255, blank=True, null=True)
    product_dimension = models.CharField(max_length=255, blank=True, null=True)
    batteries = models.CharField(max_length=255, default="Included")
    item_model_no = models.CharField(max_length=255, blank=True, null=True)
    processor_brand = models.CharField(max_length=255, blank=True, null=True)
    processor_type = models.CharField(max_length=255, blank=True, null=True)
    ram_size = models.CharField(max_length=255, blank=True, null=True)
    memory_technology = models.CharField(max_length=255, blank=True, null=True)
    hdd_technology = models.CharField(max_length=255, blank=True, null=True)
    hdd_size = models.CharField(max_length=255, blank=True, null=True)
    ssd_size = models.CharField(max_length=255, blank=True, null=True)
    speaker_discription = models.CharField(max_length=255, blank=True, null=True)
    graphic_processor = models.CharField(max_length=255, blank=True, null=True)
    graphic_card_size = models.CharField(max_length=255, blank=True, null=True)
    connectivity_type = models.CharField(max_length=255, blank=True, null=True)
    no_of_usb2_ports = models.CharField(max_length=255, blank=True, null=True)
    no_of_usb3_ports = models.CharField(max_length=255, blank=True, null=True)
    no_of_hdmi_ports = models.CharField(max_length=255, blank=True, null=True)
    no_of_audio_out_ports = models.CharField(max_length=255, blank=True, null=True)
    no_of_microphone_ports = models.CharField(max_length=255, blank=True, null=True)
    power_source = models.CharField(max_length=255, default="Battery Powered", blank=True, null=True)
    os = models.CharField(max_length=255, default="Windows 10 Home", blank=True, null=True)
    avg_battery_standby = models.CharField(max_length=255, blank=True, null=True)
    avg_battery_life = models.CharField(max_length=255, blank=True, null=True)
    lithium_energy_battery_content = models.CharField(max_length=255, blank=True, null=True)
    included_components = models.CharField(max_length=255, default="Laptop, Battery, AC Adapter, User Guide, Manuals", blank=True, null=True)
    warrenty = models.CharField(max_length=255, default="1 Year", blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

class Sensor(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    brand = models.CharField(max_length=50, blank=True, null=True)
    model = models.CharField(max_length=50, blank=True, null=True)
    item_weight = models.CharField(max_length=50, blank=True, null=True)
    product_dim = models.CharField(max_length=50, blank=True, null=True)
    part_no = models.CharField(max_length=50, blank=True, null=True)
    battery = models.CharField(max_length=50, blank=True, null=True)
    audio_focus = models.CharField(max_length=50, blank=True, null=True)
    programmable_btn = models.CharField(max_length=50, blank=True, null=True)
    color = models.CharField(max_length=50, blank=True, null=True)
    hardware_interface = models.CharField(max_length=50, blank=True, null=True)
    voltage = models.CharField(max_length=50, blank=True, null=True)
    color_screen = models.CharField(max_length=50, blank=True, null=True)
    screen_size = models.CharField(max_length=50, blank=True, null=True)
    compabitable_devises = models.CharField(max_length=50, blank=True, null=True)
    property_1 = models.TextField(blank=True, null=True)
    property_2 = models.TextField(blank=True, null=True)
    property_3 = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title
    
class ElectronicComponent(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    brand = models.CharField(max_length=50, blank=True, null=True)
    model = models.CharField(max_length=50, blank=True, null=True)
    item_weight = models.CharField(max_length=50, blank=True, null=True)
    product_dim = models.CharField(max_length=50, blank=True, null=True)
    part_no = models.CharField(max_length=50, blank=True, null=True)
    battery = models.CharField(max_length=50, blank=True, null=True)
    audi_focus = models.CharField(max_length=50, blank=True, null=True)
    programmable_btn = models.CharField(max_length=50, blank=True, null=True)
    color = models.CharField(max_length=50, blank=True, null=True)
    hardware_interface = models.CharField(max_length=50, blank=True, null=True)
    voltage = models.CharField(max_length=50, blank=True, null=True)
    color_screen = models.CharField(max_length=50, blank=True, null=True)
    screen_size = models.CharField(max_length=50, blank=True, null=True)
    compabitable_devises = models.CharField(max_length=50, blank=True, null=True)
    property_1 = models.TextField(blank=True, null=True)
    property_2 = models.TextField(blank=True, null=True)
    property_3 = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    is_published = models.BooleanField(default=True)
    main_image = models.ImageField(upload_to='producs/', blank=True, null=True)
    image_1 = models.ImageField(upload_to='producs/', blank=True, null=True)
    image_2 = models.ImageField(upload_to='producs/', blank=True, null=True)
    image_3 = models.ImageField(upload_to='producs/', blank=True, null=True)
    image_4 = models.ImageField(upload_to='producs/', blank=True, null=True)
    image_5 = models.ImageField(upload_to='producs/', blank=True, null=True)
    image_6 = models.ImageField(upload_to='producs/', blank=True, null=True)
    image_7 = models.ImageField(upload_to='producs/', blank=True, null=True)
    image_8 = models.ImageField(upload_to='producs/', blank=True, null=True)
    mrp = models.IntegerField()
    deal_price = models.IntegerField()
    rating = models.IntegerField()
    is_nocost = models.BooleanField(default=False)
    feature_1 = models.CharField(max_length=255, blank=True, null=True)
    feature_2 = models.CharField(max_length=255, blank=True, null=True)
    feature_3 = models.CharField(max_length=255, blank=True, null=True)
    feature_4 = models.CharField(max_length=255, blank=True, null=True)
    feature_5 = models.CharField(max_length=255, blank=True, null=True)
    feature_6 = models.CharField(max_length=255, blank=True, null=True)
    feature_7 = models.CharField(max_length=255, blank=True, null=True)
    feature_8 = models.CharField(max_length=255, blank=True, null=True)
    style = models.CharField(max_length=255, blank=True, null=True)
    color = models.CharField(max_length=255, blank=True, null=True)
    pro_banner_1 = models.ImageField(upload_to='producs/', blank=True, null=True)
    pro_banner_2 = models.ImageField(upload_to='producs/', blank=True, null=True)

products/views.py
from django.shortcuts import render, redirect
from .models import *
from cart.models import Cart
import math
from django.template.defaulttags import register
from django.contrib.auth.models import User



def index(request):
    banners = Banner.objects.all().order_by("-created_at").first()
    laptops = Product.objects.filter(category_id=2)
    return render(request, "index.html", context={'banners':banners, 'laptops':laptops})

def laptops(request):
    products = Product.objects.filter(category_id=2)
    context = {'products':products,
                }
    return render(request, "products/categories.html", context)

def mobiles(request):
    products = Product.objects.filter(category_id=1)
    context = {'products':products}
    return render(request, "products/categories.html", context)

def sensors(request):
    products = Product.objects.filter(category_id=3)
    context = {'products':products}
    return render(request, "products/categories.html", context)

def electronic_components(request):
    products = Product.objects.filter(category_id=4)
    context = {'products':products}
    return render(request, "products/categories.html", context)

def rating(request, id):
    rating = id
    context = {'rating':rating}
    print(rating)
    return reverse("laptops", context)

def product(request, product_id):
    product = Product.objects.get(id=product_id)
    rating = list(range(product.rating))
    user = request.user
    cart = []
    if user.is_authenticated:
        cart_items = Cart.objects.filter(user=request.user)
        for i in cart_items:
            cart.append(i.product.id)
    rating_un = list(range(5-len(rating)))
    save = ((product.mrp-product.deal_price)/product.mrp)*100
    context = {
        'product':product,
        'rating': rating,
        'rating_un': rating_un,
        'cart':cart,
        'save': save
    }
    return render(request, "products/product_descr.html", context)

templates/_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="cart_item">
        <div></div>
            <div class="item_image"><img src="{{product.main_image.url}}" alt="{{product.title}}">
            </div>
        <div class="item_description">
                <h2>{{product.title}}</h2>
            <div class="item_price">
                <h3>Rs.{{product.deal_price}}</h3> 
                <del>Rs.{{product.mrp}}</del>  
                <!-- <del>MRP</del> -->
            </div>
            <div class="rating">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
            </div>
            <p>Qty: 1</p>
            <p style="display:inline;">No cost EMI Available</p>
        </div>
        </div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Mulish&display=swap" rel="stylesheet">
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/categories.css' %}">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <style>
    {% block style %}{% endblock %}
    </style>
</head>
<body>

    <div class="search-box">
        <form method="POST" action="{% url 'search' %}">
        {% csrf_token %}
            <input type="text" placeholder="Search" name="inp" 
            {% if search_input %} value={{search_input}} {% endif %}>
        </form>
    </div>

    <nav class="1">
        <input type="checkbox" id='check'>
        <label for="check">
            <i class="fa fa-bars" id='menu'></i>
        </label>
        <a href="{% url 'products:index' %}"><label class='logo'>SHOPIFY</label></a>
        <a class='cart' href="{% url 'cart:cart' %}"><i class="fa fa-shopping-cart"></i></a>
        <ul>
            <div class="dropdown">
                {% if user.is_authenticated %}
                <button class="dropbtn">Hello, {{user.first_name}} <i class="fa fa-caret-down"></i></button>
                {% endif %}
                <div class="dropdown-content">
                  <a href="{% url 'user_profile:profile' %}">My Profile</a>
                  <a href="{% url 'buy:my_orders' %}">My Orders</a>
                  <a href="#">Coupons</a>
                  <a href="#">Whishlist</a>
                  <a href="#">Notifications</a>
                  <a href="{% url 'accounts:logout' %}">Logout</a>
                </div>
              </div> 
              <div class='user_ac'>


                <label for="check">
                    <i class="fa fa-times" id='menu'></i>
                </label>
        
                <br>
                {% if user.is_authenticated %}
                <li><a href="{% url 'user_profile:profile' %}">Hello, {{user.first_name}}</a></li>
                <li><a href="{% url 'buy:my_orders' %}">My Orders</a></li>
                <li><a href="#">Coupons</a></li>
                <li><a href="#">Wishlist</a></li>
                <li><a href="#">Notifications</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% endif %}
              </div>
              {% if not user.is_authenticated %}
              <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
              <li><a href="{% url 'accounts:login' %}">Login</a></li>
              {% endif %}
              <li><a class='cart1' href="{% url 'cart:cart' %}"><i class="fa fa-shopping-cart"></i> cart</a></li>  
        </ul>  
    </nav><div class="bel_nav"><h1></h1></div>

        <div class="category" align='center'>
            <!-- <div class="cat_web"> -->
                <ul>
                    <li><a href="{% url 'products:laptops' %}">Laptops</a></li>
                    <li><a href="{% url 'products:mobiles' %}">Mobiles</a></li>
                    <li><a href="{% url 'products:sensors' %}">Sensors</a></li>
                    <li><a href="{% url 'products:electronic_components' %}">Electronic Components</a></li>
               </ul>
            <!-- </div> -->
            <!-- <div class="cat_mobile">
                <button class="dropbtn">Categories <i class="fa fa-caret-down"></i></button>
                <div class="dropdown-content">
                  <a href="{% url 'products:laptops' %}">Laptops</a>
                  <a href="{% url 'products:mobiles' %}">Mobiles</a>
                  <a href="{% url 'products:sensors' %}">Sensors</a>
                  <a href="{% url 'products:electronic_components' %}">Electronic Components</a>
                </div>
            </div> -->
        </div>
        
        {% block content %}
          
        {% endblock %}
    <div class="footer">
        <a href="#">About us</a> 
        <a href="#">Condition of Use and Sale</a> 
        <a href="#">Privacy Notice</a><br>
        <a href="#">Facebook</a> 
        <a href="#">Twitter</a> 
        <a href="#">Instagram</a> 
        <p>&copy;2020 SHOPIFY</p>
    </div>
<script src="{% static 'js/main.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
</body>

templates/email_confirm.html
        <h1 style="margin-top: 10px; margin-bottom:5px;">Product</h1>
        {% include "_product.html" %}
        <br>
        <h1 style="margin-bottom:5px;">Shipping Address</h1>
        <div class="address">
                <h4 class="inline">{{address.first_name}} {{address.last_name}}</address></h4>
                <p>{{address.locality}}</p>
                <p>{{address.area}}</p>
                <p>{{address.city}}-{{address.pin}}.</p>
                <p>Mob: {{address.mobile}}</p>
                {% if address.landmark %}
                <p>Landmark: {{address.landmark}}</p>
                {% endif %}
        </div>

templates/email_otp.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Hi {{ user.first_name }}, This is the OTP to reset your password: {{otp}}<br> 
</body>
</html>

templates/email_temp_html.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        button{
            background-color:#07CB79;
            border-radius: 20px;
        }

    </style>
</head>
<body>
    Hi {{ user.first_name }}, Please click on the below button to confirm your registration<br>
    <a href="http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}" ><button style="font-weight:bolder; color:white; padding-top:10px; padding-bottom:8px; padding-left:10px; padding-right:10px; border:2px solid white; text-align:center;">Click here to confirm</button></a>
 
</body>
</html>